### ISSUE TITLE
Lower resolutions causing an error for metrics_set2

### ISSUE THREAD

**Issue by stukrause** [ptompalski/lidRmetrics#2]
Hello, this is a useful package. I especially find the Lefsky metrics useful when gridded. I get an error when I try lower resolutions (res <15) for metrics_set2. Is there a way around this? 

`library(lidR)
library(lidRmetrics)

LASfile <- system.file("extdata", "Megaplot.laz", package="lidR")
las <- readLAS(LASfile)

m3 <- grid_metrics(las, ~metrics_set2(X, Y, Z), res = 10)

Error in `[.data.table`(las@data, , if (!anyNA(.BY)) c(eval(call)), by = cells) : 
  Column 68 of result for group 292 is type 'double' but expecting type 'integer'. Column types must be consistent for each group.
In addition: There were 21 warnings (use warnings() to see them)
`

**Comment by ptompalski** [comment]
Hi @stukrause,
thanks for pointing out a bug. I think I fixed it, but please let me know if the code works for you. 
P

**Comment by stukrause** [comment]
Thanks, yes it works great, your fix did it. Cheers
