### ISSUE TITLE
Error using metrics_set2 in pixel_metrics function with modified arguments

### ISSUE THREAD

**Issue by mickeycampbell** [ptompalski/lidRmetrics#3]
Hello!

I am running into a few issues using your `metrics_set2()` function within the lidR `pixel_metrics()` function. I was able to successfully use it when using `cloud_metrics()` on a series of small point clouds, clipped to the extent of some field plots, as follows:
```
plot.mets <- cloud_metrics(plot.laz, ~metrics_set2(x = X,
                                                   y = Y,
                                                   z = Z,
                                                   zmin = 0.5,
                                                   zintervals = c(0,0.5,1,2,4,8)))
```
However, when I try using the `metrics_set2()` function in `pixel_metrics()`, I get errors. I've tried a few different approaches... First, I tried it with a single LAZ file:
```
pix.mets <- pixel_metrics(test.las, ~metrics_set2(x = X,
                                                  y = Y,
                                                  z = Z,
                                                  zmin = 0.5,
                                                  zintervals = c(0,0.5,1,2,4,8)),
                          res = 25)
```
I receive the following error: ` Error in filter(., Z >= zmin) : object 'Z' not found `. FWIW, I get the same error when I remove the `~` in front of `metrics_set2()`. When I put `Z` in quotation marks (i.e., defining it as a character variable), I get the following error: ` Error in z - zmean : non-numeric argument to binary operator `. Interestingly, when I remove some of the function argments, and simplify it as below (per your example in the documentation), it runs without issue:
```
pix.mets <- pixel_metrics(test.las, ~metrics_set2(X,Y,Z),
                          res = 25)
```
The same thing applies when I run it on a LAScatalog -- with just `~metrics_set2(X,Y,Z)` it works fine but when I define additional parameters, it says `object 'Z' not found`. When I run it in parallel using `plan(multisession, workers = 12L)`, I do have to explicitly define `~lidRmetrics::metrics_set2()` instead of just `~metrics_set2()`, otherwise it returns `could not find function "metrics_set2"`. But, other than that, the same issue of not being able to define additional function arguments persists.

FWIW, I recognize that your library was developed for use with the older `grid_metrics()` function, so I tried to run it with that, and I'm getting the same errors.

I'm using R v4.0.5, lidR v4.0.1, and lidRmetrics v0.0.1, on a Windows OS.

Thanks in advance for any help you can provide!

**Comment by ptompalski** [comment]
Hi, thanks for the detailed report, will definitely help me identify the issue. 

Without testing anything all I can say is that most probably there are pixels (25 x 25 m in your case) that do not have any points above 0. I will run some tests, try to recreate the issue, and correct the code. Stay tuned.

**Comment by ptompalski** [comment]
Well.. this took some time. My honest apologies to you @mickeycampbell. The issue wasn't easy to identify and I gave up when looking at the code a year ago. 

Anyway, it is now fixed. The following code works:

```
library(lidR)
library(lidRmetrics)
LASfile <- system.file("extdata", "Megaplot.laz", package="lidR")
las <- readLAS(LASfile, select = "*", filter = "-keep_random_fraction 0.5")


pix.mets <- pixel_metrics(las, metrics_set2(x = X,
                                            y = Y,
                                            z = Z,
                                            zmin = 0.5,
                                            zintervals = c(0,0.5,1,2,4,8)),
                          res = 25)
```
